### Get Twitch game "Minecraft"
GET {{API_ENDPOINT}}/{{GAMES_PATH}}?name=Minecraft
Client-Id: {{CLIENT_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}

### Get Top games
GET {{API_ENDPOINT}}/{{GAMES_PATH}}/top?first=30
Client-Id: {{CLIENT_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}