@baseUrl = https://api.twitch.tv/helix
@gamesPath = games

### Get Twitch game "Minecraft"
GET {{baseUrl}}/{{gamesPath}}?name=Minecraft
Client-Id: {{$dotenv CLIENT_ID}}
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}