@baseUrl = https://api.twitch.tv/helix
@usersPath = users

### Get Twitch user "ansishihi"
GET {{baseUrl}}/{{usersPath}}?login=ansishihi
Client-Id: {{$dotenv CLIENT_ID}}
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}